// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QnAAPI.Models;

namespace Poll_Pall_Light.Migrations.QnAItem
{
    [DbContext(typeof(QnAItemContext))]
    [Migration("20210611083312_QnAAPI")]
    partial class QnAAPI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QnAAPI.Models.QnAItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AItemId")
                        .HasColumnType("int");

                    b.Property<int>("QItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QnAItems");
                });
#pragma warning restore 612, 618
        }
    }
}
